
webapp-a:
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    port: 80
  autoscaling:
    enabled: true
    kind: HorizontalPodAutoscaler


super-secret:
  replicaCount: 1
  hostPath: /host-share/data
  initContainers:
    image: busybox:1.36
  image:
    repository: hashicorp/http-echo
    tag: "0.2.3"
  configMapName: new-super-secret-app-config
  secretName: new-super-secret-app-secrets
  queues:
    - all
  resources:
    requests:
      cpu: 450m
      memory: 750Mi
  priorityClassName: secret-priority
  autoscaling:
    enabled: true
    kind: "Keda"
  secret:
    enabled: true
    name: new-super-secret-app-secrets
    remoteKey: app/secrets/db-creds
    store:
      kind: SecretStore
      name: vault-backend
    useFakeForTesting: true









