apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-super-secret-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-super-secret-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: new-super-secret-app
    spec:
      volumes:
        - name: data
          hostPath:
            path: /host-share/data
            type: DirectoryOrCreate
      initContainers:
        - name: mnt-change-permissions
          image: busybox:1.36
          command:
            - sh
              - '-c'
              - |-
              find /mnt/data -exec chown 1000:1001 \
              {} + 2>/dev/null
          resources: {}
          volumeMounts:
            - name: data
              mountPath: /mnt/data 
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      containers:
        - name: new-super-secret-app
          image: new-super-secret-app:v2
          envFrom:
            - configMapRef:
                name: new-super-secret-app-config
            - secretRef:
                name: new-super-secret-app-secrets
          env:
            - name: QUEUES
              value: '["all"]'
          volumeMounts:
            - name: data
              mountPath: /mnt/data
          resources:
            requests:
              cpu: 450m
              memory: 750Mi
      terminationGracePeriodSeconds: 0
      priorityClassName: secret-priority
