{{- if .Values.newSuperSecretApp.secret.useFakeForTesting }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.newSuperSecretApp.secret.name }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: "127.0.0.1"
  DB_USERNAME: "psql"
  DB_PASSWORD: "superhardpassword"
{{- end }}
