{{- if .Values.autoscaling.enabled }}
{{- if eq .Values.autoscaling.kind "Keda" }}

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
{{ include "webapp.labels" . | indent 4 }}
spec:
  scaleTargetRef:
{{ include "webapp.selectorLabels" . | indent 4 }}
  minReplicaCount: 0
  cooldownPeriod: 300
  triggers:
    - type: cron
      metadata:
        timezone: Asia/Kolkata
        start: "0 6 * * *"
        end: "0 20 * * *"
        desiredReplicas: "10"

{{- end }}
{{- end }}
